### ISSUE TITLE
Option to delete RenPy games on completion but preserve saves

### ISSUE THREAD

**Issue by LoopyLoot** [Willy-JL/F95Checker#101]
So basically, I was wondering if it would be possible to implement a feature where users can choose to delete everything inside a game folder except the saves folder when marking a game as “Played” to help save disk space. That way, when a new version comes out, you can just download it and transfer the saves folder.

**Comment by ParaplegicRacehorse** [comment]
Unless Willy-JL is planning to include an un/install system, I think this is impractical. Especially since every game engine handles saves differently. Even different versions of the same game engine place savefiles in different places. Take renpy, for example. Some editions store saves in `<gameroot>/game/saves/` while other editions store saves in your `$HOME/.renpy`. That's a stupid amount of logic to add to this tool just for renpy. Now stack godot, bevy, rpgm, unity, etc. to that and you get an entirely unmanageable gamesave backup system.
