### ISSUE TITLE
Program starting problem

### ISSUE THREAD

**Issue by By-PorfecTo** [Willy-JL/F95Checker#15]
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

program log

**Comment by By-PorfecTo** [comment]
my python version 3.10.5

**Comment by Willy-JL** [comment]
You’re on windows and you’re running from source? Are you using main branch or the release source zip? Did you install the requirements with pip? If so are you sure it did so successfully, because installing requirements by compiling can be tricky on windows...

**Comment by By-PorfecTo** [comment]
git+https://github.com/Willy-JL/pyopengl.git@fix-numpy#subdirectory=accelerate
git+https://github.com/pyimgui/pyimgui.git@dev/version-2.0
git+https://github.com/Willy-JL/pyopengl.git@fix-numpy

requirements.txt 

not downloading gives error

**Comment by Willy-JL** [comment]
Yes, those are required to run this tool. Also their public version is outdated / not working properly so they must be installed from source for now. This means you need a lot of development packages installed in order to compile them, otherwise pip will error if they are not installed. Namely you probably need visual studio installed, and thats like 9 gb of a program. I suggest just using the prebuilt windows download.

**Comment by By-PorfecTo** [comment]
I tried to open it with visual studio code and it gave an error on line 21 I tried to install it with pip the room gave an error
![ScreenShot_20220730010931](https://user-images.githubusercontent.com/92230690/181852534-2b613666-fb9d-4597-8fbf-939932c64227.png)
![ScreenShot_20220730011122](https://user-images.githubusercontent.com/92230690/181852545-5d6455ed-d022-47fb-9d57-dc74de344113.png)

**Comment by Willy-JL** [comment]
You are not listening to me.

Visual studio and visual studio code ARE NOT the same thing. Visual studio code is a text editor, visual studio is an IDE that has integrated the build tools necessary to install requirements with pip.

Uvloop is a plug-in that speeds up the program. Uvloop does not work on windows. You do not need to install it. Vscode gives an error because it is stupid and does not understand the line above:
```python
if globals.os is not Os.Windows:
    import uvloop
```
It will not use uvloop on windows, so it will not give an error, but vscode is stupid so it tells you it is an error.

Please, don't waste my time with these basic questions and problems about Python, this is a relatively complex program and I can't teach you the basics of Python. Either you learn on your own, or you use the prebuilt F95Checker-Windows.exe that DOES NOT require anything with Python or pip.

**Comment by By-PorfecTo** [comment]
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

I solved the problem windows 10 does not see the path C:\python310\Lib\site-packages\PyQt6\Qt6\plugins\platforms even if you download the requirements
I added path to windows manually and it opened

**Comment by By-PorfecTo** [comment]
Thanks for your help and sorry if I offended you.
