### ISSUE TITLE
Fix some developer parsing strings

### ISSUE THREAD

**Issue by just-Addict** [Willy-JL/F95Checker#22]
The developer of [Intimate Relations](https://f95zone.to/threads/intimate-relations-v0-80-ptolemy.1970/) isn't properly detected. 

The thread uses `Developer/Publisher: `  instead of just `Developer:` which causes F95Checker to trip and showing the slash as developer name.

**Comment by Willy-JL** [comment]
I can't test right now because I'm not home but I've improved the developer and analogous string detection in 9.4 beta, can you try to see if it's fixed with the latest build from the GitHub actions tab?

**Comment by just-Addict** [comment]
I tested with 9.4 beta 514 and it now lists the developer as "Unknown" after doing a full recheck

**Comment by Willy-JL** [comment]
I might have a better plan for this. Only search for strings that start with "Developer" (and analogous) in order to catch also stuff that is not bolded properly, then add all following text except links except the first one (sometimes the developer name itself is a link) until a "br" line break, then remove all known "developer" and analogous strings from the beginning of the plain text (so in this games case only "Developer" would match but also "/publisher" would get removed as plain text), remove the known social text (patreon an the like) and finally strip all parentheses / separators `()/-|` (they sometimes are around the developer social links). Will have to see how well this works but I'm hopeful

**Comment by Willy-JL** [comment]
Looks like im gonna backtrack on what i proposed before, thats just too much. What ill do is fix a few small oversights with the system i had made that had it working suboptimally and lead to the problem you were facing
