### ISSUE TITLE
Show forum rating value

### ISSUE THREAD

**Issue by essaion** [Willy-JL/F95Checker#30]
Well, that's all in the subject, actually. :)

**Comment by Willy-JL** [comment]
can you better explain what you mean by public note?

**Comment by essaion** [comment]
I was thinking to the current rating of any thread, which is the mean of the notes attributed by the user.
On a second thought, a better information could be "mean of the notes attributed during the last X months" or "mean of the latest X notes". Not sure there is an easy way for doing so though. :/

**Comment by Willy-JL** [comment]
Ok i take it that by mean you mean the average, thats what makes the most sense to me. So youre asking for the forum rating to be visible. Should be very doable, i didnt do it because it would cause confusion with the personal rating that is already present. But with a separate column and with another detail entry it should be acceptable. Also im just going to take the value shown on the thread page, im not gonna calculate the average myself.

**Comment by Willy-JL** [comment]
Released in [version 9.6](https://github.com/Willy-JL/F95Checker/releases/tag/9.6)
