### ISSUE TITLE
[Feature request or bugfix] "Installed" and "Played" status are reset when a new version is detected

### ISSUE THREAD

**Issue by essaion** [Willy-JL/F95Checker#32]
Hello there,

Not sure if this is a feature request or a bugfix, but I was surprised to see that the detection of a new version of a game resets the "installed" and "played" flags. At the very least I would suggest to add a setting that would allow to change this behaviour and prevent the flags to get reset. Another possibility would be to, maybe, change the colour of the flags, or the colour of the line, or... don't know what easily feasible, actually. My gut feeling is that those flags should not get reset at all, or at least to let the user decide if they should.

Cheers.

**Comment by Willy-JL** [comment]
Its intended behavior since this tool is meant to track game updates. If you use this tool chances are you are interested in having our games up to date, and if a new version is detected, well the latest version is no longer installed. If at some point you marked the game as installed, it remembers this. If a new version is found, it will show both version numbers next to each other with appropriate icons, so you know it is still installed, but the checkbox is empty because the *latest* version is not installed. Check the FAQ section for more info

Kind of the same applies for the played behavior, since an update generally means that there is new content you havent played yet... but the played checkbox is independant from the installed checkbox, so say the update was just a bugfix, yo ucan tick the played box but not the installed one. so this way you know "ah, this is installed but i dont have the exact latest version, but i did play all the content available"

**Comment by essaion** [comment]
I am confused. The FAQ does indeed mention this, and I somehow managed not to see it although I could have swear that I had read it. Same thing goes for my other ticket about adding the rating column - I managed to skip that information while I was reading... err... skimming through the FAQ. Lazy brain of mine. Thanks for your patient answer, and my sincere apologies for wasting your time.
