### ISSUE TITLE
Tick the "Installed" flag when seleting EXE

### ISSUE THREAD

**Issue by essaion** [Willy-JL/F95Checker#33]
Hello there,

It's all in the title, again. ;)

Cheers. I'm done for the moment, FWIW. ^^

**Comment by essaion** [comment]
At least one ticket that is not a total screw-up! Yay! \o/

**Comment by ipaqi** [comment]
Actually disagree, because of the relationship between the Installed flag and the installeds vs available version info. Currently marking the installed flag causes the "installed version" info to be updated to the latest available.

So if you want to get this done at some point, a new state needs to be available for the "installed" flag, of "old version installed". Maybe like a greyed out Checkmark.

**Comment by Willy-JL** [comment]
Thats true, ive actually found myself in this situation recently, so yeah not gonna do this

**Comment by essaion** [comment]
Hey, is there any problem with my eyes or did you actually implement a new “installed” state, as @ipaqi suggested? If so, well, back to the feature request, I suppose…? ^_^'
(I understand that this assumes that the user is selecting the latest version of the .EXE file, which should be the case more often than not)

**Comment by Willy-JL** [comment]
Still not really keen on adding this... like yeah now there is a clearer different between installed outdated and installed latest, but then, say it is unchecked and the user selects an exe... should it be marked as latest? no, thats an assumption... mark as outdated installed? well, also an assumption, and would also require the user to type in the exact version... and if instead the installed checkbox is half set, then selecting an exe should do what? mark as installed latest? again, an assumption that could easily not be true... now that there can also be multiple executables per game and that the checkbox has 3 states, i dont want to confuse the users further with more debatable behavior and assumptions
