### ISSUE TITLE
Pressing "enter" in the search bar when it's empty shouldn't attempt to search F95zone for anything

### ISSUE THREAD

**Issue by ipaqi** [Willy-JL/F95Checker#38]
Pressing "enter" in the search bar when it's empty shouldn't attempt to search F95zone for anything.

Instead, it should just clear the search filter and return to the baseline. It already does that after it throws an exception when trying to search F95Z for an empty string, so let's just cut the middleman.

**Comment by Willy-JL** [comment]
I think the problem you’re having is related to the current release, it has a bug where deleting a character from input fields doesn’t delete it, but replaces with a null character. So you see it fine, but behind the scenes the text isn’t techno empty so it tries to search for that. It’s fixed in the newest beta, I’ll make an update soon enough

**Comment by Willy-JL** [comment]
Fix released in 9.4
