### ISSUE TITLE
Feature request: Kanban board view

### ISSUE THREAD

**Issue by ogkimra** [Willy-JL/F95Checker#42]
Hey
Have you thought about adding a kanban board as a view that users can switch to(from table or gallery view)

![images (1).jpeg](https://user-images.githubusercontent.com/32086892/200730720-0e55e6e1-5db0-4392-8903-a65c895e2652.jpeg)

Along with Custom tags(#19) as headers for the view a kanban board will look really good.

To show all the planning, playing, finished, dropped(or custom tags) etc in separate list is a very good QOL update imho

**Comment by Willy-JL** [comment]
Maybe... we will see...

**Comment by Willy-JL** [comment]
This however brings up an interesting problem with the custom tags implementation, I'll explain my doubts in #19

**Comment by Willy-JL** [comment]
Give it a shot in [build 810](https://github.com/Willy-JL/F95Checker/actions/runs/3599090090) and let me know how it feels!

In the end I went for the easy solutions to keep things simple, both on developer and user side. Games can have multiple, or none, custom labels. In list/grid/kanban view you get small tag icons next to the names with the first character of each word in the label name, and you can easily add icons to the labels so you can make it look pretty neat. Finally, for kanban view i made it so each label is its own column, and since each game can have multiple or no labels, each game can show in multiple kanban columns. This is why i decided to disable drag and drop for manual sorting in kanban, to manual sort youll need grid or list mode. Otherwise kanban view respects all other settings: filters and sorting work just the same as everywhere else, just that, again, same games can be in multiple columns, but inside of each column you can be assured that theyre sorted appropriately. Of course there is an additional column for non labelled games. I wanted to make the columns hideable but that gave many issues with cell sizes and table width, so I decided not to. But you can reorder the label columns around, even though i realize just while writing this that i made it forget table settings so that build in particular wont remember the order you change to after a restart, will fix in a bit. However if you add or remove labels it will probably forget the order anyway, because it counts as a different table configuration.

**Comment by Willy-JL** [comment]
Update: fixed the saving issue, now kanban column order saves properly. Also fixed another issue I found with the background color of the game cells.

So yeah try [build 812](https://github.com/Willy-JL/F95Checker/actions/runs/3599176025) and let me know how it goes!

**Comment by Willy-JL** [comment]
Ok these should be the last changes. So i noticed a bug with the context menu where having the game in multiple columns duplicated the right click menu buttons. Trying to fix that I ended up putting each kanban column into its own scrolling area, and to be honest i really like how that works now, so yeah 2 birds with 1 stone as they say.

[Build 815](https://github.com/Willy-JL/F95Checker/actions/runs/3599589108) should have a pretty final implementation of this hopefully

**Comment by Willy-JL** [comment]
Released in [version 9.6](https://github.com/Willy-JL/F95Checker/releases/tag/9.6)
