### ISSUE TITLE
Folder dialogue to select exe, doesn't allow mouse navigating on Windows.

### ISSUE THREAD

**Issue by FaceCrap** [Willy-JL/F95Checker#44]
Like I posted [here](https://f95zone.to/threads/f95checker-willyjl.44173/post-9422539), either I'm doing something wrong, which I doubt, or the folder navigation window to select an exe doesn't allow double-clicking to navigate to the selected folder. 
The only way I can select an exe at the moment is typing/pasting the full path to the game folder in the top input box.

**Comment by Willy-JL** [comment]
This must be a problem on your end, because i haven't changed anything about that part of the filepicker between 9.4 and 9.5. The only change is that I added the filter textbox underneath. In any case, I can't manage to reproduce the issue so nothing I can do, again, has to be something odd on your end :/

**Comment by Willy-JL** [comment]
Actually i kinda just managed to reproduce it, but its weird. What i got to happen is that I click twice in the same frame, so it doesnt count as a double click. So either you're not human and can click insanely fast, or you have some very low fps. Try clicking slower?

**Comment by FaceCrap** [comment]
WOOT!... You hit the nail right on the head... To further reduce CPU usage, even though it wasn't an issue to begin with for me, I had changed the VSync Ration to 1:10, which indeed causes the FPS to sink below 10 FPS. So I just set it to uncapped (1:0) and bam... folder navigation works...  damn who would have thought... great call.

**Comment by Willy-JL** [comment]
> perhaps set a minimum FPS ? Or a max on the ratio?

there is a max, which is 1:10. its so "high" because for example there exist monitors with up to 360 hz, so at that point a 1:10 ratio gets you to 30 fps. i consider 30 fps the barrier under which an interface becomes unusable, or very unpleasant to use, so i feel like thats a good compromise.



> So I just set it to uncapped (1:0) and bam... folder navigation works...

would highly recommend against that however. it means that it will try to render faster than what your monitor is capable of showing, bringing nothing more to the table other than higher cpu usage and strain. sensible values are 1:1, and 1:2 if you dont mind a bit of input lag and jitteryness in image output.



> Too bad this doesn't fix the iOS RD Client thing... even though annoying it's not the end of the world... would be nice though if that could be fixed.

to be completely honest that sounds like a pretty bad remote desktop client if it manages to change how the desktop works enough to break an application completely. i would suggest using something like anydesk, that might work better?

**Comment by FaceCrap** [comment]
> to be completely honest that sounds like a pretty bad remote desktop client if it manages to change how the desktop works enough to break an application completely. 
>i would suggest using something like anydesk, that might work better?

It's MS's official RDP Client... and F95Checker is so far the only application with this issue.

Besides... Anydesk requires a server app installed on the host AND, (and this is a deal breaker) 

- requires you to enter an ID (provided by the host) on the client to connect
- requires confirmation of the access request on the host 

It's a totally different beast, this is something that is only usable as a support tool, not as a remote access tool. And it doesn't use RDP...

**Comment by Willy-JL** [comment]
> * requires you to enter an ID (provided by the host) on the client to connect
> 
>     * requires confirmation of the access request on the host
> 
> 
> It's a totally different beast, this is something that is only usable when there's someone present on the other end to provide the ID and to grant access, not as a remote access tool to an unmanned workstation.

not really, no. thats if you want to help someone by remoting into their machine with them present,but yo ucan setup unattended access for your own machine. set a password and that will stay the same, and no interaction required on the unattended pc. i can speak from experience, anydesk is my go-to
