### ISSUE TITLE
Add a third value to the Played column like you did for the Installed column

### ISSUE THREAD

**Issue by ipaqi** [Willy-JL/F95Checker#45]
I use the Played column to mark when I've played through everything in a particular version of a game.

It would be useful if, when a version changes, it was set to an in-between value like you've done for the Installed field

**Comment by FaceCrap** [comment]
What would that in-between value then represent? There's only two options possible, you've either played the new update or you haven't... if the installed field indicates there's an update, the Played field consequently shows as non-played since you've not yet set the Installed field to having downloaded and installed that update...and once you do have the update installed and marked as such, the Played field stays blank until you mark it manually as having played.

**Comment by Willy-JL** [comment]
I mean i get the proposal:
- the installed icon has 3 states: not installed, outdated install, latest installed
- the played icon has 2 states: not played , played
- proposal is played icon has 3 states: never played, played an earlier version, played latest version

but i think the tradeoff between complexity (both for user experience and code) is far more compared to the advantages... i mean to know how much you played on older versions you can just see the saves you have in the game... and implementing this would also bring the problem of where to put the "last fully played version" information, because a second update badge would be outrageous, and the info popup is crowded enough. and also as said before, confusion for the average user. so im sorry but ill have to pass on this one
