### ISSUE TITLE
Wine support for linux

### ISSUE THREAD

**Issue by KJNeko** [Willy-JL/F95Checker#56]
Running games on linux should have the ability to specify a [wine](https://www.winehq.org/) executable and wine prefix (See [WINEPREFIX](https://wiki.winehq.org/Wine_User%27s_Guide#WINEPREFIX)) to run games on when provided.

Having this ability would allow people unable to get a native executable to run games through the application itself. Having the ability to provide a wine prefix would allow specific setups aswell for games that require it (Such as japanese locale) without effecting other prefixes/wine applications running

(Edit: better wording/format)

**Comment by Willy-JL** [comment]
I personally am a linux user and find the current setup to be quite satisfactory. You can see for yourself here
https://github.com/Willy-JL/F95Checker/blob/70bc13893580fa27832b3e06919cbaaed88b10aa/modules/callbacks.py#L117-L151
that currently when launching an executable, on windows it leaves windows to decide what to do, while on linux and macos it does a bunch of other stuff. First it checks for a .exe or .msi extension and for a shebang. If either is present and the file is not marked executable already, it marks it. Then it does the same for renpy libs, since unzipping renpy games often results in non-executable libs and games that fail to launch. So really what should happen is that by marking the .exe files executable, they are automatically handled by wine. Or atleast that works fine for me. As for custom prefixes, while i see your point, ive never found myself in such a situation, ive always used the system prefix, and if you really need to you can just use scripts:

`/games/xyz/launch.sh`:
```bash
#!/bin/bash
WINEPREFIX=xyz wine game.exe
```

So yeah im afraid im going to have to pass on this one, just too niche to add prefix support and wine support should be handled by the os some other place, as the default app to launch .exe files
