### ISSUE TITLE
Suggestion: Game name installed/played color reversed

### ISSUE THREAD

**Issue by RalkeyOfficial** [Willy-JL/F95Checker#59]
While using the software, I noticed that played games turn the title color white and installed games remain red.

From a user's perspective, this is actually quite confusing,
since the white color of the title makes me think I should be able to play it.

I would expect that installed games turn white instead of played games,
which makes more sense, as installed games are playable and should show some sort of priority over uninstalled games.

**Comment by Willy-JL** [comment]
The idea is that games you are yet to finish playing are colored with the accent color of the program. Its not red to indicate something negative, it is red because its the default accent color. In my case its blue. And accent colors are used to highlight things and bring attention to them, in this case to show you that you haven't played these games, so you should probably be more interested in those instead of the ones you already played. If instead you have more 'unplayed' games than played ones, and the white stands out more than the red accent, then its on you xD
