### ISSUE TITLE
Change data folder path

### ISSUE THREAD

**Issue by k0ng1** [Willy-JL/F95Checker#6]
Option to choose where to store data. that is not in roaming

sorry for my english

**Comment by Willy-JL** [comment]
I think this option would lead to way too much confusion and weird edge cases... what you should do instead is make a symbolic link: move the config and replace the one in roaming with a symbolic link to the actual file somewhere else on the disk. I might add an example on how to do this for the next update.

**Comment by CuddleBear92** [comment]
Can't this be portable though? i can see how people playing with their paths can cause bugs, issues and user error. But a portable path is pretty neat and tidy in general. also easier to just host it on an external drive for those that does that.

**Comment by Willy-JL** [comment]
It was portable originally, but that caused severe issues with updating. If it were a single executable file, then maybe, but with Python freezing it’s not really acceptable and updating requires swapping hundreds to thousands of files, so ignoring data files could get tricky, fast.



> i can see how people playing with their paths can cause bugs, issues and user error.

Having it look in multiple places actually causes more confusion. A regular user won’t care about this feature. An advanced user who would care about this feature is advanced enough to make a symlink. Having this feature instead can cause issues when “where did my games go?!?” if it starts using a portable config instead of a centralized one
