### ISSUE TITLE
Game saves backup?

### ISSUE THREAD

**Issue by SalehA-55** [Willy-JL/F95Checker#76]
Hey, can you add a feature to backup Game saves? 

Allow to me explain my vision:
You show the app where the game save folder is (just like how you assign the .exe file location). 
It then will copy the save folder to an already assigned "backup" folder (or it can be in the "Roaming\f95checker directory").

- The backup can then be updated by a simple button in the game info. 
- In the backup folder you can keep a log of all the changes, serving as a reference to the user. In addition, to prevent any backup loss, you can still keep the last 3 backups of a specific game. (in my opinion, this shouldn't be a problem since the saves don't take much space)
- You can also add a button in the app menu to update all the game saves. (similar to the "Refresh" button)
- You can also add a feature to backup all the saves when the app is launched. 
- You can also in the backed up save folder add the directory from where the it was copied. Honestly seems pointless, but if it was easy to implement why not.

These are some ideas. And in case you decide to give them a shot, they don't have to be all implemented. 

Thank you

**Comment by SalehA-55** [comment]
Honestly, you have made many eye-opening points. And to be truthful, I am but a mealy simple user without any coding knowledge. But, the biggest issue seems to be the save folder location. To which I suggested that it can be user defined. Although, automating the prosses as you've suggested, is clearly a much better solution (i.e. the overrule method).

In terms of making it user defined, I feel that I haven't made it clear as to what exactly I mean, thus allow me to explain: 

- I suggest to focus the whole backing-up prosses from `%appdata%` directory, this is because not every game keeps the saves in its directory, thus the need to copy it form `%appdata%`. In addition, not every game is made with RenPy, which is why it is not hard to find a game that does not keep the save file in its directory. And even in terms of other OS, making it user defined seems the much easier alternative. 
- As a user I can know where the `define config.save_directory` in the `options.rpy`.
- Even if the `options.rpy` was not easily readable as you have mentioned with the whole 'UnRen' difficulties. You can manually find the save loction in `%appdata%` (or any other directory), and tell F95Checker where it is. 

Ultimately, I may be missing a few crucial points, and in a little over my head here. As to the above mentioned concerns, a mixture of my suggestions and @FaceCrap, may have the the best possible outcome.

**Comment by FaceCrap** [comment]
@SalehA-55 I must admit that I totally overlooked the fact there's also non-Ren'Py games. You are correct, those would have completely different save locations.

In hindsight, I don't expect F95Checker will ever acquire the option to modify the `<exename>.py` file directly. That would very much go beyond the scope of the program, plus, like you reminded me, this only applies to Ren'Py games, it's probably even harder to determine the save location for non-Ren'Py games, let alone to overrule these locations.

Manually entering the save file location seems then only viable option, but that still leaves the problem of finding out which folder in the `%appdata%` structure is associated with which Ren'Py game. Luckily the majority of the games I play(ed) use names that are easily recognizable, but there are those which use completely unrelatable names. 

As for non-Ren'Py games, I have only played 2 or 3 of those... and these don't even store their saves in the `%appdata%` folder (which normally points to `C:\Users\%USERNAME%\AppData\Roaming\`) but in a sibling folder at `C:\Users\%USERNAME%\AppData\LocalLow\` 
Not much of an issue since `%appdata%\..\LocalLow\` will put you there, and `%localappdata%` will give you the `local` folder (on the off-chance a game stores it saves there)

Still, it's going to be a helluva endavour to even come up with a solution given the pitfalls in identifying where saves get stored.

**Comment by Willy-JL** [comment]
yeah no thanks...

too many different formats to support for engines that im notinterested in myself, and most engines (and especially renpy being the most popular) already store in a user directory

also games tend to change config structure or inner workings between versions, so i dont think this is a good idea...
