### ISSUE TITLE
User customizable Tabs

### ISSUE THREAD

**Issue by ghost** [Willy-JL/F95Checker#81]
Hey, you've probably seen this [suggestion](https://f95zone.to/threads/f95checker-willyjl.44173/post-11415053)

I think it's interesting and will be useful to many people (including myself).
I have already written some code, and opened this issue to ask if this is something you would accept as a PR.

Essentially it would involve:
1. Adding new table that will store thread id, full url, and some text (for notes)
2. Adding new global and a struct (or maybe simple dict)
3. Changing some code in `extension.js` and `webview.py` to add new context actions (something like "Add this link to bookmarks") and new icons.
4. Adding GUI code to display a table with search bar and buttons to edit, delete, etc.

Something like this. Clicking "Open" opens popup(dialog) window with stored bookmarks.

![Untitled](https://github.com/Willy-JL/F95Checker/assets/134188774/1694e8b4-e89d-49d0-9f23-7538a53d4eb6)

Would appreciate to hear your opinion on this one

**Comment by Willy-JL** [comment]
yea this sounds like a good idea and approach!

im not too sold on them being called "bookmarks" since then they would confuse with the forum bookmarks

deffo should be its own struct, a basic dataclass will do, but not a dict

and it will also need some additions to the rpc in order to handle he bookmark events from the extension / webview

but yes, please go ahead!

**Comment by FaceCrap** [comment]
I had to go back to the forum to read about this suggestion, because at first I didn't see the idea behind it (like was commented in the forum)
To be honest, I think that would be something I'd be using. I already have a bunch of games added to F95Checker which I am interested in, but not to the extent that I want to play them at this point,
Like was suggested as an alternative, I too created a label to distinguish them from my other games. But like the post in the forum mentioned, that distinction is not visible on the forum, and neither in F95Checker during an update check.
So I would welcome such an addition with open arms.
You got my vote @littleraisins

**Comment by littleraisins** [comment]
Here is some ideas for naming:

Scribbles
Flags
Reminders
Memos
F-Notes (silly, but might work)

I'm not native English speaker, maybe you guys can come up with something better

**Comment by Willy-JL** [comment]
Checkmarks is another work for checkbox, like the box with a tick in it that you can toggle on or off, so that's a no.

Flag is used visually already in the interface for the finished flag icon

F-Notes I'm not a huge fan of

Scribbles... meh

Memos and Reminders however, those sound great... can't choose myself what sounds better

**Comment by FaceCrap** [comment]
My vote would be Reminders then... I get too much of an office feeling with Memos 🤣

**Comment by Willy-JL** [comment]
Reminders it is then

**Comment by U-s-e-r-42** [comment]
Is it possible to make the name changeable?

**Comment by username279** [comment]
Please don't make archived games automatically moved to a separate list. It's just that I saw that someone suggested to make that the archived games are sent to a separate list. I am now using the littleraisin's build, and in other lists I archive games, and I do not want that the archived games would be removed from there.

I mean, there are three lists, and each list has archive games, and I don't really want them mixed up in the "archive list".
Also, it would be cool to be able to change the name of the lists, as well as the characters and their color (extension shows on the site in which list added games),  as suggested in [this post](https://f95zone.to/threads/f95checker-willyjl.44173/post-12387977).

**Comment by Willy-JL** [comment]
now implemented in a different way via #111 and #112 . now theres tabs, you can move your games to whatever tab you want and customize how that tab looks
